import { Platform, StyleSheet } from 'react-native';

export const colors = {
  bg: '#F7EFE7',
  card: '#FFFFFF',
  brown: '#7B5338',
  darkBrown: '#4A3024',
  lightBrown: '#C99A6B',
  orange: '#E7A56B',
  peach: '#FFE0C2',
  cream: '#FFF8EF',
  border: '#E8D8CA',
  text: '#30241D',
  muted: '#8D7D72',
  red: '#D85A4D',
  green: '#5A9B63',
  yellow: '#E2A334',
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.bg, paddingTop: Platform.OS === 'android' ? 24 : 0 },
  appBody: { flex: 1 },
  loginSafe: { flex: 1, backgroundColor: colors.bg },
  loginContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  logoCircle: { width: 68, height: 68, borderRadius: 34, backgroundColor: colors.brown, alignItems: 'center', justifyContent: 'center', marginBottom: 20 },
  logoText: { color: colors.card, fontSize: 28 },
  loginTitle: { color: colors.darkBrown, fontSize: 32, fontWeight: '800' },
  loginSubtitle: { color: colors.muted, fontSize: 15, marginTop: 6, marginBottom: 28 },
  loginCard: { width: '100%', maxWidth: 390, backgroundColor: colors.card, borderRadius: 20, padding: 22, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },
  forgot: { color: colors.brown, fontWeight: '700', textAlign: 'right', marginTop: 2, marginBottom: 16 },
  roleLabel: { color: colors.darkBrown, fontWeight: '700', marginBottom: 8 },
  roleRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 14 },
  support: { textAlign: 'center', color: colors.darkBrown, fontSize: 12, fontWeight: '600', marginTop: 16 },
  coffeeDecoration: { marginTop: 30, width: 90, height: 90, borderRadius: 45, backgroundColor: 'rgba(123, 83, 56, 0.10)', alignItems: 'center', justifyContent: 'center' },
  coffeeDecorationText: { fontSize: 50, opacity: 0.25 },
  header: { paddingHorizontal: 18, paddingTop: 8, paddingBottom: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerLeft: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, marginRight: 10 },
  avatarText: { fontSize: 20 },
  headerTitle: { color: colors.darkBrown, fontSize: 17, fontWeight: '800' },
  headerSub: { color: colors.muted, fontSize: 12 },
  bellBtn: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border },
  bellText: { color: colors.brown, fontSize: 18, fontWeight: '800' },
  screen: { paddingHorizontal: 18, paddingBottom: 90 },
  screenTitle: { color: colors.darkBrown, fontSize: 23, fontWeight: '900', marginBottom: 14 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 16 },
  statCard: { minWidth: '30%', flexGrow: 1, borderRadius: 16, padding: 14, marginRight: 8, marginBottom: 8 },
  statBrown: { backgroundColor: colors.cream },
  statRed: { backgroundColor: '#FFE9E6' },
  statGreen: { backgroundColor: '#EAF7EA' },
  statYellow: { backgroundColor: '#FFF4D9' },
  statOrange: { backgroundColor: colors.peach },
  statTitle: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  statValue: { color: colors.darkBrown, fontSize: 20, fontWeight: '900', marginTop: 5 },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, marginTop: 4 },
  sectionTitle: { color: colors.darkBrown, fontSize: 16, fontWeight: '800' },
  sectionAction: { color: colors.orange, fontSize: 12, fontWeight: '800' },
  miniCard: { backgroundColor: colors.card, borderRadius: 16, padding: 14, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: colors.brown, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  cardTitle: { color: colors.darkBrown, fontSize: 14, fontWeight: '800' },
  mutedText: { color: colors.muted, fontSize: 12, marginTop: 3 },
  smallText: { color: colors.darkBrown, fontSize: 12, marginTop: 8 },
  performanceCard: { backgroundColor: colors.card, borderRadius: 18, padding: 18, marginTop: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  percentCircle: { width: 78, height: 78, borderRadius: 39, borderWidth: 8, borderColor: colors.brown, alignItems: 'center', justifyContent: 'center' },
  percentText: { color: colors.darkBrown, fontWeight: '900' },
  tabRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 14 },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 18, backgroundColor: colors.cream, marginRight: 8, marginBottom: 6 },
  chipActive: { backgroundColor: colors.brown },
  chipText: { color: colors.brown, fontSize: 12, fontWeight: '800' },
  chipTextActive: { color: colors.card },
  smallChip: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 14, backgroundColor: colors.cream, borderWidth: 1, borderColor: colors.border, marginRight: 8, marginBottom: 8 },
  smallChipActive: { backgroundColor: colors.brown, borderColor: colors.brown },
  smallChipText: { color: colors.brown, fontWeight: '800', fontSize: 12 },
  smallChipTextActive: { color: colors.card },
  orderCardLarge: { backgroundColor: colors.card, borderRadius: 18, padding: 16, marginBottom: 14, borderLeftWidth: 4, borderLeftColor: colors.orange },
  orderTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  orderCode: { color: colors.darkBrown, fontWeight: '900', fontSize: 16 },
  itemLine: { color: colors.text, fontSize: 13, marginTop: 5 },
  noteText: { color: colors.muted, fontSize: 12, marginTop: 10, fontStyle: 'italic' },
  rowButtons: { flexDirection: 'row', marginTop: 12 },
  smallBtn: { flex: 1, backgroundColor: colors.brown, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingVertical: 10, marginRight: 8 },
  smallBtnOutline: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.brown },
  smallBtnText: { color: colors.card, fontSize: 12, fontWeight: '900' },
  smallBtnTextOutline: { color: colors.brown },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  searchBox: { backgroundColor: colors.card, borderRadius: 16, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, marginBottom: 14, flexDirection: 'row', alignItems: 'center' },
  inventoryCard: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: 16, padding: 14, marginBottom: 12 },
  sideLine: { width: 4, borderRadius: 2, backgroundColor: colors.green, marginRight: 12 },
  sideLineRed: { backgroundColor: colors.red },
  sideLineYellow: { backgroundColor: colors.yellow },
  stockText: { color: colors.darkBrown, fontSize: 20, fontWeight: '900', marginTop: 8 },
  flex1: { flex: 1 },
  productRow: { flexDirection: 'row', backgroundColor: colors.card, borderRadius: 16, padding: 12, marginBottom: 10, alignItems: 'center' },
  productImage: { width: 64, height: 64, borderRadius: 14, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  productEmoji: { fontSize: 30 },
  editBtn: { width: 36, height: 36, borderRadius: 18, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center' },
  editText: { color: colors.brown, fontSize: 20, fontWeight: '900' },
  moneyCard: { backgroundColor: colors.card, borderRadius: 18, padding: 18, marginBottom: 12 },
  moneyCardLight: { backgroundColor: '#FFE9E6', borderRadius: 18, padding: 18, marginBottom: 12 },
  moneyCardDark: { backgroundColor: colors.brown, borderRadius: 18, padding: 18, marginBottom: 16 },
  moneyLabel: { color: colors.muted, fontWeight: '800', fontSize: 12 },
  moneyLabelLight: { color: colors.cream, fontWeight: '800', fontSize: 12 },
  moneyValue: { color: colors.darkBrown, fontSize: 28, fontWeight: '900', marginTop: 8 },
  moneyValueRed: { color: colors.red, fontSize: 28, fontWeight: '900', marginTop: 8 },
  moneyValueLight: { color: colors.card, fontSize: 28, fontWeight: '900', marginTop: 8 },
  actionCard: { backgroundColor: colors.brown, borderRadius: 18, padding: 18, marginBottom: 16 },
  actionTitle: { color: colors.card, fontWeight: '900', fontSize: 17, marginBottom: 6 },
  movementRow: { backgroundColor: colors.card, borderRadius: 16, padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center' },
  movementIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.cream, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  amountText: { color: colors.green, fontWeight: '900' },
  amountOut: { color: colors.red },
  paymentCard: { backgroundColor: colors.card, borderRadius: 18, padding: 18, marginBottom: 16 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  priceLabel: { color: colors.muted, fontWeight: '700' },
  priceValue: { color: colors.darkBrown, fontWeight: '800' },
  priceStrong: { color: colors.darkBrown, fontSize: 18, fontWeight: '900' },
  separator: { height: 1, backgroundColor: colors.border, marginVertical: 10 },
  formCard: { backgroundColor: colors.card, borderRadius: 18, padding: 18, marginBottom: 16 },
  productGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 12 },
  productTile: { width: '48%', backgroundColor: colors.card, borderRadius: 18, padding: 12, marginBottom: 12 },
  tileEmoji: { fontSize: 42, backgroundColor: colors.cream, borderRadius: 14, textAlign: 'center', paddingVertical: 12, marginBottom: 10 },
  tileTitle: { color: colors.darkBrown, fontWeight: '900' },
  tilePrice: { color: colors.muted, marginTop: 4 },
  addText: { color: colors.orange, fontWeight: '900', marginTop: 6 },
  inputGroup: { marginBottom: 14 },
  inputLabel: { color: colors.darkBrown, fontWeight: '800', fontSize: 13, marginBottom: 8 },
  inputBox: { minHeight: 48, borderWidth: 1, borderColor: colors.border, borderRadius: 24, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', backgroundColor: colors.card },
  inputIcon: { color: colors.muted, marginRight: 8 },
  input: { flex: 1, color: colors.text, paddingVertical: 10 },
  inputMultiline: { minHeight: 70, textAlignVertical: 'top' },
  brownBtn: { minHeight: 52, backgroundColor: colors.brown, borderRadius: 26, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, marginTop: 10 },
  brownBtnText: { color: colors.card, fontWeight: '900', fontSize: 15 },
  pressed: { opacity: 0.75 },
  pill: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12 },
  pillBrown: { backgroundColor: colors.cream },
  pillGreen: { backgroundColor: '#EAF7EA' },
  pillYellow: { backgroundColor: '#FFF4D9' },
  pillRed: { backgroundColor: '#FFE9E6' },
  pillText: { color: colors.darkBrown, fontSize: 10, fontWeight: '900' },
  navbar: { position: 'absolute', left: 14, right: 14, bottom: Platform.OS === 'ios' ? 18 : 12, backgroundColor: colors.card, borderRadius: 26, minHeight: 66, paddingVertical: 8, flexDirection: 'row', justifyContent: 'space-around', shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 12, elevation: 5 },
  navItem: { alignItems: 'center', justifyContent: 'center', flex: 1 },
  navIcon: { width: 34, height: 26, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  navIconActive: { backgroundColor: colors.peach },
  navIconText: { color: colors.muted, fontWeight: '900' },
  navIconTextActive: { color: colors.brown },
  navLabel: { color: colors.muted, fontSize: 10, marginTop: 4, fontWeight: '700' },
  navLabelActive: { color: colors.brown },
});
